const brailleQuiz = [
    { question: "점자는 시각장애인이 문자를 읽을 수 있도록 만든 체계이다.", answer: "O" },
    { question: "점자는 손가락으로 만져서 읽을 수 있다.", answer: "O" },
    { question: "점자는 총 9개의 점으로 구성되어 있다.", answer: "X" },
    { question: "한글 점자에는 초성, 중성, 종성의 구분이 없다.", answer: "X" },
    { question: "점자는 영어, 중국어, 일본어 등 여러 언어로도 존재한다.", answer: "O" },
    { question: "한글 점자의 기본 구조는 2행 3열의 6점 셀이다.", answer: "O" },
    { question: "점자를 읽을 때는 왼손으로만 읽는다.", answer: "X" },
    { question: "점자는 시각장애인뿐만 아니라 청각장애인도 사용한다.", answer: "X" },
    { question: "점자에는 문장부호도 존재한다.", answer: "O" },
    { question: "한글 점자는 ‘훈맹정음’이라고도 불린다.", answer: "O" },
    { question: "점자는 1개 점만으로도 모든 글자를 표현할 수 있다.", answer: "X" },
    { question: "점자는 특수기호나 수학기호도 표현할 수 있다.", answer: "O" },
    { question: "점자는 책처럼 페이지를 넘기며 읽는다.", answer: "O" },
    { question: "점자는 144가지 조합이 가능하다.", answer: "O" },
    { question: "점자 프린터는 점자를 출력해주는 기계다.", answer: "O" },
    { question: "모든 시각장애인이 점자를 사용할 수 있는 것은 아니다.", answer: "O" },
    { question: "한글 점자는 영어 점자와 동일한 규칙을 따른다.", answer: "X" },
    { question: "점자는 촉각이 둔한 사람도 쉽게 배울 수 있다.", answer: "X" },
    { question: "점자 교육은 유치원부터 시작되기도 한다.", answer: "O" },
    { question: "점자 도서는 일반 서점에서도 쉽게 구할 수 있다.", answer: "X" },
    { question: "점자는 화면에 표시되는 전자기기로도 읽을 수 있다.", answer: "O" },
    { question: "한글 점자는 초성, 중성, 종성의 순서로 구성된다.", answer: "O" },
    { question: "점자는 시각장애인의 정보 접근 권리를 위한 중요한 수단이다.", answer: "O" },
    { question: "점자에는 숫자와 문자를 구별할 수 있는 표시 기호가 있다.", answer: "O" },
    { question: "점자는 시각적으로도 확인이 가능하다.", answer: "O" },
    { question: "점자를 빠르게 읽는 사람은 분당 200자 이상 읽는다.", answer: "O" },
    { question: "점자 블록은 점자 문자와 같은 원리로 만들어졌다.", answer: "X" },
    { question: "점자를 배울 때 점자 타자기를 사용하기도 한다.", answer: "O" },
    { question: "컴퓨터 자판으로도 점자를 입력할 수 있다.", answer: "O" },
    { question: "세계 점자의 날은 매년 1월 4일이다.", answer: "O" }
  ];

export default brailleQuiz;